"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { FileText, ArrowLeft } from "lucide-react";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-slate-900">
            {/* Header */}
            <header className="border-b border-gray-800 bg-slate-950/50 backdrop-blur-sm sticky top-0 z-50">
                <div className="container-custom py-4">
                    <Link
                        href="/"
                        className="inline-flex items-center space-x-2 text-gray-300 hover:text-white transition-colors"
                    >
                        <ArrowLeft size={20} />
                        <span>Back to Home</span>
                    </Link>
                </div>
            </header>

            {/* Content */}
            <div className="container-custom py-16">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="max-w-4xl mx-auto"
                >
                    {/* Title */}
                    <div className="text-center mb-12">
                        <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-primary mb-6">
                            <FileText size={32} className="text-white" />
                        </div>
                        <h1 className="text-4xl md:text-5xl font-bold mb-4">
                            Terms of <span className="gradient-text">Service</span>
                        </h1>
                        <p className="text-gray-400">Last updated: December 14, 2024</p>
                    </div>

                    {/* Content */}
                    <div className="glass-card p-8 md:p-12 space-y-8 text-gray-300">
                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">Agreement to Terms</h2>
                            <p className="leading-relaxed">
                                By accessing and using this portfolio website ("the Site"), you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to these Terms of Service, please do not use the Site.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">Use License</h2>
                            <p className="leading-relaxed mb-4">
                                Permission is granted to temporarily view the materials (information or software) on this Site for personal, non-commercial use only. This is the grant of a license, not a transfer of title, and under this license you may not:
                            </p>
                            <ul className="list-disc list-inside space-y-2 ml-4">
                                <li>Modify or copy the materials</li>
                                <li>Use the materials for any commercial purpose</li>
                                <li>Attempt to decompile or reverse engineer any software on the Site</li>
                                <li>Remove any copyright or proprietary notations from the materials</li>
                                <li>Transfer the materials to another person or "mirror" the materials on any other server</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">AI Chat Assistant</h2>
                            <p className="leading-relaxed mb-4">
                                The AI chat assistant is provided for informational purposes only:
                            </p>
                            <ul className="list-disc list-inside space-y-2 ml-4">
                                <li>Responses are generated by AI and may not always be accurate</li>
                                <li>The AI is trained on portfolio information and may not have real-time updates</li>
                                <li>Do not share sensitive personal information in chat conversations</li>
                                <li>Chat history is not permanently stored</li>
                                <li>I reserve the right to monitor chat usage to improve the service</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">Contact Form</h2>
                            <p className="leading-relaxed mb-4">
                                When using the contact form:
                            </p>
                            <ul className="list-disc list-inside space-y-2 ml-4">
                                <li>Provide accurate and truthful information</li>
                                <li>Do not submit spam, malicious content, or unsolicited commercial messages</li>
                                <li>Respect intellectual property rights</li>
                                <li>Do not attempt to exploit or harm the Site's infrastructure</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">Intellectual Property</h2>
                            <p className="leading-relaxed mb-4">
                                All content on this Site, including but not limited to:
                            </p>
                            <ul className="list-disc list-inside space-y-2 ml-4">
                                <li>Text, graphics, logos, images</li>
                                <li>Code and software</li>
                                <li>Design and layout</li>
                                <li>Project descriptions and case studies</li>
                            </ul>
                            <p className="leading-relaxed mt-4">
                                is the property of MD. Shahadot Hossain and is protected by international copyright laws. Unauthorized use may violate copyright, trademark, and other laws.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">Disclaimer</h2>
                            <p className="leading-relaxed mb-4">
                                The materials on this Site are provided on an 'as is' basis. I make no warranties, expressed or implied, and hereby disclaim and negate all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
                            </p>
                            <p className="leading-relaxed">
                                Further, I do not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on the Site or otherwise relating to such materials or on any sites linked to this Site.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">Limitations</h2>
                            <p className="leading-relaxed">
                                In no event shall MD. Shahadot Hossain or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on this Site, even if I or an authorized representative has been notified orally or in writing of the possibility of such damage.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">Accuracy of Materials</h2>
                            <p className="leading-relaxed">
                                The materials appearing on this Site could include technical, typographical, or photographic errors. I do not warrant that any of the materials on the Site are accurate, complete, or current. I may make changes to the materials contained on the Site at any time without notice.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">Links</h2>
                            <p className="leading-relaxed">
                                I have not reviewed all of the sites linked to this Site and am not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by me. Use of any such linked website is at the user's own risk.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">Third-Party Services</h2>
                            <p className="leading-relaxed mb-4">
                                This Site uses third-party services including:
                            </p>
                            <ul className="list-disc list-inside space-y-2 ml-4">
                                <li>Google Gemini AI for chat functionality</li>
                                <li>Resend for email delivery</li>
                                <li>GitHub API for repository statistics</li>
                                <li>Vercel for hosting</li>
                            </ul>
                            <p className="leading-relaxed mt-4">
                                These services are governed by their own terms of service and privacy policies.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">Modifications</h2>
                            <p className="leading-relaxed">
                                I may revise these Terms of Service at any time without notice. By using this Site, you are agreeing to be bound by the then-current version of these Terms of Service.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">Governing Law</h2>
                            <p className="leading-relaxed">
                                These terms and conditions are governed by and construed in accordance with the laws of Bangladesh, and you irrevocably submit to the exclusive jurisdiction of the courts in that location.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-white mb-4">Contact Information</h2>
                            <p className="leading-relaxed">
                                If you have any questions about these Terms of Service, please contact me:
                            </p>
                            <div className="mt-4 p-4 bg-slate-800 rounded-lg">
                                <p className="mb-2"><strong className="text-white">Email:</strong> shahadotrahat786@gmail.com</p>
                                <p className="mb-2"><strong className="text-white">Phone:</strong> +880-1775-020-582</p>
                                <p><strong className="text-white">Location:</strong> Dhaka, Bangladesh</p>
                            </div>
                        </section>
                    </div>

                    {/* Back Button */}
                    <div className="mt-12 text-center">
                        <Link href="/" className="btn-primary inline-flex items-center space-x-2">
                            <ArrowLeft size={18} />
                            <span>Back to Home</span>
                        </Link>
                    </div>
                </motion.div>
            </div>
        </div>
    );
}
